module.exports = {
  RECEIVE_ALL_NOTEBOOKS: "RECEIVE_ALL_NOTEBOOKS",
  RECEIVE_CURRENT_NOTEBOOK: "RECEIVE_CURRENT_NOTEBOOK",
  CREATE_NOTEBOOK: "CREATE_NOTEBOOK",
  UPDATE_NOTEBOOK: "UPDATE_NOTEBOOK",
  REMOVE_NOTEBOOK: "REMOVE_NOTEBOOK",
  CLEAR_CURRENT_NOTEBOOK: "CLEAR_CURRENT_NOTEBOOK"
};
