module.exports = {
  RECEIVE_ALL_NOTEBOOKS: "RECEIVE_ALL_NOTEBOOKS",
  RECEIVE_SINGLE_NOTEBOOK: "RECEIVE_SINGLE_NOTEBOOK",
  CREATE_NOTEBOOK: "CREATE_NOTEBOOK",
  UPDATE_NOTEBOOK: "UPDATE_NOTEBOOK",
  REMOVE_NOTEBOOK: "REMOVE_NOTEBOOK"
};
